[package]
name = "musicrate"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
color-eyre = "0.6.5"
ratatui = { version = "0.29.0", features = ["all-widgets"] }
